### ISSUE TITLE
MSCloudIdUtils - Spaces in Documents folder cause error during Install-MSCloudIdUtilsModule

### ISSUE THREAD

**Issue by JefTek** [ramical/Samples#3]
When installing on a machine where the documents folder contains a space in the environment variables ([Environment]::GetFolderPath("MyDocuments")), it causes an error during the download and installation of the ADAL library files with files not found error.

Example:  The Documents folder is in C:\users\joeuser\OneDrive - Contoso\Documents

**Comment by ramical** [comment]
Fixed in version 1.0.0.1

**Comment by scrubbles** [comment]
I still get the error.

https://github.com/ramical/Samples/blob/4cc0ffc2323159b8cbafbea943a5dafafb05a4ef/MSCloudIdUtils/MSCloudIdUtils.psm1#L1285

I copied what you had done on line L1282 and the below seems to work now for me:

$nugetDownloadExpression = '& "' + $modulePath + '\Nugets\nuget.exe" install Microsoft.IdentityModel.Clients.ActiveDirectory -Version 2.14.201151115 -OutputDirectory ' + '"' + $modulePath + '\Nugets" | out-null'
